### ISSUE TITLE
No devices in dev branch

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/NetAlertX#779]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

I wanted to quickly inform you that the latest builds of the dev branch do not allow the display of devices, despite having forced the cache cleaning
Thanks

### Expected Behavior

show devices

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @corasaniti ,

Could you please confirm you have refreshed the cache 🔄 and cleared the browser cache as well? You can also try pulling the latest `-dev` image as I implemented some settings improvements and changes recently.

**Comment by corasaniti** [comment]
@jokob-sk 
Cleared cashe from GUI and browser. Devices are displayed once but when I go back to home they disappear
PS: where do I find GUI settings to change the fields to display for device display.
![Immagine 2024-09-02 084926](https://github.com/user-attachments/assets/27bce666-9b91-464b-a9df-85b79f96e8e6)

**Comment by jokob-sk** [comment]
Thanks for confirming!

1.  Could you please let me know what browser are you using? If you are not using Firefox or Chrome, could you please try one of those instead?
2.  Are there any errors in the console of the browser?

I moved the columns setting into Settings -> UI Settings

**Comment by corasaniti** [comment]
> Thanks for confirming!
> 
> 1. Could you please let me know what browser are you using? If you are not using Firefox or Chrome, could you please try one of those instead?
I use Chrome

> 2. Are there any errors in the console of the browser?
Attacched console screen  no errror but devices disappared

![Immagine 2024-09-02 115957](https://github.com/user-attachments/assets/cd25871e-f183-42a5-86a6-69ce6774c4f2)

> 
> I moved the columns setting into Settings -> UI Settings
ok but how I change columng in device View?

![11111](https://github.com/user-attachments/assets/ebdffcb3-34d9-44f3-ad35-4366f631ab8b)

**Comment by jokob-sk** [comment]
Thank you @corasaniti for the screenshots! Hummm, there are no errors, however other users on the dev branch (e.g. #766 ) seem not to have this issue. I just published a new image on the dev branch with a version/timestamp setting to determine if the app was upgraded/the backend has changed. Can you try pulling the latest image, opening the app in an incognito browser and posting your build timestamp? It should be equal to the one below: 

![image](https://github.com/user-attachments/assets/d78b17be-b807-45c5-a890-611eb75014c7)

**Comment by corasaniti** [comment]
@jokob-sk 
Sure, I cleared cashe browser and force clear with the button from the GUI

This is my timestamp
![Cattura](https://github.com/user-attachments/assets/9c870b73-97ea-4ff2-91a9-488fa00fe92d)

But I can't change add/remove columns in devices view from settings. Dont see any button add/remove

![Cattura2](https://github.com/user-attachments/assets/40b6ccb9-5b66-4d2e-a616-c71f06f9d31b)

After clear cache, devices are now visible
![Cattura3](https://github.com/user-attachments/assets/a1adac39-630b-4117-a719-952b26aa0066)


Thanks in advance
PC

**Comment by corasaniti** [comment]
@jokob-sk 
I keep having problems with the latest build-dev
1. Missing device in device view (clean and forced cache browser)
![nodev](https://github.com/user-attachments/assets/be43e44c-1061-40d1-a0ac-89bca5b89619)

2. Missing ADD/remove button in gui settings columns
![ADD](https://github.com/user-attachments/assets/7655d60c-5cba-410c-ba6b-ecf74d409d0b)


I take this opportunity to ask for information on the status of the device.
Why do I see some devices marked offline with the "green offline" label and instead I see other devices marked online with the "grey online" label

![Cattura2](https://github.com/user-attachments/assets/379ff887-d19b-45a7-a65f-0d6fbf751954)

![Cattura1](https://github.com/user-attachments/assets/a77c40d1-b2b1-4f4f-b378-42f3e6b7cb51)




Thanks

**Comment by jokob-sk** [comment]
Thanks for the feedback! I added 3 buttons and a better description to describe how to change that setting: 

![image](https://github.com/user-attachments/assets/63f6eb78-c406-4af7-8b22-e7972e7d6a66)


This should be in the-dev branch in about 15 min

**Comment by corasaniti** [comment]
@jokob-sk 
Unfortunately the problem still exists with the latest dev build

The devices continue to NOT be visible. I see them the first time after I clear the cache but every time I return to the home page the devices disappear
![Immagine 2024-09-05 110834](https://github.com/user-attachments/assets/901bcabd-85f6-4618-9878-00735ec326d7)


Furthermore I do not see the complete ui settings section. I cannot see the entire complete section. There are only the buttons but I cannot perform any operation (see screen)

![Immagine 2024-09-05 111048](https://github.com/user-attachments/assets/c936c369-397c-407b-ad72-94f8db14e3d8)


I love NetalertX but I have to note that in this last period it has become very complex. 
Every user would like to have the features much simpler. This is my consideration
Thanks

**Comment by jokob-sk** [comment]
Hi @corasaniti,

Thanks a lot for the detailed information.

I really appreciate your ongoing feedback and help to make NAX better.

I only can spend 1-2 h on the project every couple of days so someone helping me test the dev branch is amazing. I also understand the frustration if something does not work. So I understand if you want to switch to the production branch or a different tool.

As you said it's a complex tool that covers a lot of use cases and that means there will always be a bug here and there. In the end I don't have a team, it's only me and a few amazing contributors. 

Anyway, I just pushed some changes which hopefully fix some things. Please send me the browser dev console log screenshots if something doesn't and I'll try to fix it. 

Thanks for the ongoing help. 
J

**Comment by corasaniti** [comment]
@jokob-sk 

Ok the UI settings now works perfectly.
![Cattura0](https://github.com/user-attachments/assets/c16a6f53-5e66-4398-ba30-5d4af92c009a)

I also understood how to simulate the error of missing devices in the device list.
I like to display ALL devices without pagination.
![Cattura1](https://github.com/user-attachments/assets/bebf60f8-227b-4bcb-a7a4-7b9ba38fae7d)

If I select from the combo "All" and then go to another page of the GUI, when I return to the device list I do NOT see the devices anymore.
![Cattura2](https://github.com/user-attachments/assets/f80b4559-f330-4abf-bbe5-f0410afb7871)

If I select 10, 25 or another value in the combo, the devices appear.

![Cattura3](https://github.com/user-attachments/assets/c7b6ad54-1fd3-413f-ad7a-c9a791271085)



Recaè: if I have set "All" in the device view and go to another page when I return to the device list, these are not displayed, I am forced to change the value from the combo and return "All" to make the devices appear. No error is shown on the console.
I hope I was helpful

Thanks in advance
PC

**Comment by jokob-sk** [comment]
Thanks a lot for the details!

I think I've found the issue and fixed the `All` display error. 

I also improved the cache update to hopefully prevent this bug:

![image](https://github.com/user-attachments/assets/64c88cce-e234-486a-b44f-dc21792d2fee)

The new -dev image should be available in 15 min.

Thanks fo the ongoing support!

**Comment by corasaniti** [comment]
@jokob-sk 
Hi, With latest dev build, everything seems to be working fine. I will monitor it for a few days.
Thanks for your patience
PC

**Comment by jokob-sk** [comment]
Glad to hear that and thanks for testing!

**Comment by jokob-sk** [comment]
Releasing -> closing

**Comment by corasaniti** [comment]
@jokob-sk 
last branch DEV Unable to save setting
I have clean browser cache (opera and chrome) ad press clean cache butto in GUI

![Cattura](https://github.com/user-attachments/assets/de4ea7f7-ee55-476f-8265-a794d38b7a9d)

Thanks

**Comment by jokob-sk** [comment]
Hi @corasaniti - thanks a lot for the message! It should be fixed in the new image published in 10 minutes.

**Comment by corasaniti** [comment]
With Last DEV branch release. Chrome and Opera browser
Thanks

![Cattura](https://github.com/user-attachments/assets/98808ea9-e9a0-4f29-9ba8-698b510900f0)

Details

![333](https://github.com/user-attachments/assets/cd0177bd-b5c9-4371-b233-0d7dd49b12db)

**Comment by jokob-sk** [comment]
Hi @corasaniti,

Thanks. I know of this. The dev branch will be unstable in the next few weeks. Thanks in advance for the patience.

J

**Comment by corasaniti** [comment]
@jokob-sk 
Could you please let me know when the dev branch will be stable? I will avoid pulls until you let me know.
Thanks

**Comment by jokob-sk** [comment]
Sure thing. Thanks for the ongoing help! I'll let you know once I get closer to releasing.

**Comment by jokob-sk** [comment]
I've changed the DB structure so it's not as easy to switch back. I just pushed some charges and it should be a bit more usable now being on the dev branch. Tiles and devices filtering in the navigation are still broken though.

**Comment by jokob-sk** [comment]
Ok, the DEV branch should be pretty OK now

**Comment by corasaniti** [comment]
@jokob-sk 
the above problem still exists for the dev branch. I tried Chrome and Opera Browser
I will wait for some more releases
Thanks

![386067766-cd0177bd-b5c9-4371-b233-0d7dd49b12db](https://github.com/user-attachments/assets/c1134bec-661d-4684-85fa-1087dc1accb0)

**Comment by jokob-sk** [comment]
Hi @corasaniti ,

I just pushed a new version and added some logging to tell if the GraphQL server started up correctly. Can you check the browser console (F12) to see if the `graphQLServerStarted` variable changes from `0` to `1` during the page load?

![image](https://github.com/user-attachments/assets/18881154-b5c8-4a9b-ad19-892afad2de4c)

Please make sure you clear the cache of the app and the browser.

**Comment by corasaniti** [comment]
@jokob-sk 
from Opera debug console.
Thanks


![Cattura](https://github.com/user-attachments/assets/1fd4ec14-2ced-4891-9c0b-e2954fbde57e)

**Comment by jokob-sk** [comment]
Thanks for that!

Could you please post your debug output from `app.log` after you restart the application? 

Please try the following:

1. Restart the application
2. Visit the Devices page
3. Observe the app.log (filter with `graph`)

It should look something like this:

![image](https://github.com/user-attachments/assets/c8b4d59d-2ee1-4514-af5d-478af571fa69)


Could you please also confirm:

4. No firewall is enabled and the port `20212` is NOT used by another application
5. If you access your `<url>:20212/graphql` it is accessible and the following message is shown: 

![image](https://github.com/user-attachments/assets/6816d860-a5e3-4b68-80ea-5c61d048c282)

**Comment by corasaniti** [comment]
**app.log (filter with graph)**

```
14:56:29 [graphql_server] Starting on port ""
14:56:34 [graphql_server] Starting on port ""
14:56:39 [graphql_server] Starting on port ""
14:56:44 [graphql_server] Starting on port ""
14:56:49 [graphql_server] Starting on port ""
14:56:54 [graphql_server] Starting on port ""
08:02:40 [API] GRAPHQL_PORT or API_TOKEN is not set, will try later.
08:09:10 [graphql_server] Starting on port ""
08:09:10 [graphql_server] Starting on port ""
08:09:16 [graphql_server] Starting on port ""
08:09:21 [graphql_server] Starting on port ""
08:09:26 [graphql_server] Starting on port ""
08:09:31 [graphql_server] Starting on port ""
08:09:36 [graphql_server] Starting on port ""
08:09:42 [graphql_server] Starting on port ""
08:09:47 [graphql_server] Starting on port ""
08:09:52 [graphql_server] Starting on port ""
10:40:04 [API] GRAPHQL_PORT or API_TOKEN is not set, will try later.
```

**No firewall is enabled and the port 20212 is NOT used by another application**
No firewall and port available


**If you access your <url>:20212/graphql it is accessible and the following message is shown:**
Impossibile raggiungere il sito --> "Unable to reach site"
I hid address because it is a public IP, but I tried with local IP with the same result
See screen
![Cattura](https://github.com/user-attachments/assets/f0fdf690-c2ec-4703-9c03-9ab7c98649e7)

**Comment by corasaniti** [comment]
@jokob-sk 
![Cattura](https://github.com/user-attachments/assets/221f7430-fa9f-4485-a1db-3bf2e469066d)

**Comment by jokob-sk** [comment]
Thanks! that is the issue. Let me try to fix it today/tomorrow and I will let you know once this is resolved. Thanks for the help!

**Comment by corasaniti** [comment]
@jokob-sk 
I manually generated the tokenbut I get the same error.
Can I delete the generated token?
Thanks

**Comment by jokob-sk** [comment]
Once you generate the token you probably need to restart the application and clear the cache. But yes, you can delete it.

**Comment by cvc90** [comment]
Hi @jokob-sk, with the latest dev build it works again! 😄

**Comment by jokob-sk** [comment]
Oh nice - hope I didn't break it with the latest 2 changes 😅

**Comment by cvc90** [comment]
Ok, I found a small error, in the devices menu the URLs fail with the reverse proxies... however in the other menus they don't seem to fail, could you look into it?

**Comment by cvc90** [comment]
I just saw the PR of the solution and everything seems correct! I'm going to try the new build and let you know.

**Comment by corasaniti** [comment]
@jokob-sk 
Nothing, not even with the latest DEV build the graphql server problem has been solved

DataTables warning: table id=tableDevices - Request failed (GraphQL server might be down). URL: 0.0.0.0:20212/graphql Error: Failed to connect to 0.0.0.0 port 20212 after 0 ms: Could not connect to server

![386964411-c1134bec-661d-4684-85fa-1087dc1accb0](https://github.com/user-attachments/assets/d733aa17-205c-4e99-8df1-f47b130cdd84)

**Comment by cvc90** [comment]
@corasaniti When you create the docker do you use?

-e APP_CONF_OVERRIDE=20212

I recommend not using it, it depends on how it sometimes seems to fail when starting with the option.

**Comment by corasaniti** [comment]
@jokob-sk  I use docker-compose

```
version: "3"

services:
  netalertx:
    container_name: netalertx-dev
    image: jokobsk/netalertx-dev
    ports:
      - "20211:20211"
      - "20212:20212"
    dns:
      - 192.168.2.1
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /home/pi/docker/netalertx/config:/app/config
      - /home/pi/docker/netalertx/db/:/app/db
      - /home/pi/docker/netalertx/log/:/app/front/log
    environment:
      - TZ=Europe/Rome
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
```

**Comment by cvc90** [comment]
> @jokob-sk I use docker-compose
> 
> ```
> version: "3"
> 
> services:
>   netalertx:
>     container_name: netalertx-dev
>     image: jokobsk/netalertx-dev
>     ports:
>       - "20211:20211"
>       - "20212:20212"
>     dns:
>       - 192.168.2.1
>     network_mode: "host"
>     restart: unless-stopped
>     volumes:
>       - /home/pi/docker/netalertx/config:/app/config
>       - /home/pi/docker/netalertx/db/:/app/db
>       - /home/pi/docker/netalertx/log/:/app/front/log
>     environment:
>       - TZ=Europe/Rome
>       - HOST_USER_ID=1000
>       - HOST_USER_GID=1000
> ```

It seems to be correct, you could check if you have the GRAPHQL_PORT and API_TOKEN variables in the app.conf file

If you don't have them, add them and restart

GRAPHQL_PORT=20212
API_TOKEN='xxxxxxxxxxxx'

**Comment by jokob-sk** [comment]
@corasaniti can you please:

- stop the container
- remove the container
- remove all unused images
- rebuild the container
- open the link in an incognito window

**Comment by corasaniti** [comment]
@jokob-sk 
In a browser "incognito mode" window it works perfectly.  And yet I have cleared the browser cache.
How is this possible?

**Comment by jokob-sk** [comment]
Glad to hear that! The browser caches files so if you don't force refresh it (usually shift + reload button) it might use out of date code files.

**Comment by jokob-sk** [comment]
Releasing -> Closing
