### ISSUE TITLE
ASUSWRT log message confirm connection

### ISSUE THREAD

**Issue by netExtra** [jokob-sk/NetAlertX#972]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I "think" I connected to my router. It is on the supported list and when I wasn't connecting I kept getting timeout errors. But I'm not sure if I connected because this is the last message in the log.
[ASUSWRT] Connecting to the Router...

Nothing else about ASUSWRT after that.

### Describe the solution you'd like

If ASUSWRT is successfully connected then the log should reflect that, even if nothing is imported.If nothing is imported that should also be noted.

### Describe alternatives you've considered

N/A

### Anything else?

N/A

### Am I willing to test this? 🧪

- [x] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [x] No

**Comment by jokob-sk** [comment]
Hi @netExtra ,

Thanks for the report. 

To me this is not a big issue. Looking at the code the script returns number of devices:

```python
    mylog(
        "verbose",
        [f"[{pluginName}] Processing '{len(filtered_devices)}' connected devices"],
    )

```

I'll let @labmonkey decide if he wants to improve the logging, for me this is not an issue (low priority).

Happy for you @netExtra also to submit a PR if interested.

Thanks for understanding,
j

**Comment by labmonkey** [comment]
There is nothing 'pretty' that can be done while the plugin tries to connect. In case your credentials etc. are wrong it will try connect until it timeouts and the library that it is using has quite a long timeout for few minutes. This means in case of wrong settings the resulting output such as an error can be somewhere far later in the logs.
@jokob-sk the library that I am using has also normal python debug logs that can be turned on by `logging.basicConfig(level=logging.DEBUG)` but is this something I should put in the plugin itself? Because as I see the `LOG_LEVEL` setting is used only for the built-in logger? These logs would help users in troubleshooting.

**Comment by netExtra** [comment]
> There is nothing 'pretty' that can be done while the plugin tries to connect. In case your credentials etc. are wrong it will try connect until it timeouts and the library that it is using has quite a long timeout for few minutes. This means in case of wrong settings the resulting output such as an error can be somewhere far later in the logs. [@jokob-sk](https://github.com/jokob-sk) the library that I am using has also normal python debug logs that can be turned on by `logging.basicConfig(level=logging.DEBUG)` but is this something I should put in the plugin itself? Because as I see the `LOG_LEVEL` setting is used only for the built-in logger? These logs would help users in troubleshooting.

Thanks for the explanation. But what I am saying is that it is clear from the logs that connection failed. I would like a bit more info but at least it is clear that it failed. When (I assume that) it succeeds the app.log says nothing after the initial "connecting" message. So I'm left assuming that it has succeeded because I don't see a timeout message.

**Comment by jokob-sk** [comment]
Hummm do you have an idea how to incorporate `logging.basicConfig(level=logging.DEBUG)` into the logger @labmonkey ?

https://github.com/jokob-sk/NetAlertX/blob/main/server/logger.py

I never used the logging object before...

**Comment by netExtra** [comment]
> Hummm do you have an idea how to incorporate `logging.basicConfig(level=logging.DEBUG)` into the logger [@labmonkey](https://github.com/labmonkey) ?
> 
> https://github.com/jokob-sk/NetAlertX/blob/main/server/logger.py
> 
> I never used the logging object before...

Something like this?
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)

**Comment by jokob-sk** [comment]
I believe I fixed this.

This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first or, ideally spin up a **separate container with a separate db and config**), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

Consider sharing the app on socials 🙂🙏

Thanks in advance,
j

**Comment by netExtra** [comment]
> I believe I fixed this.
> 
> This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first or, ideally spin up a **separate container with a separate db and config**), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?
> 
> Consider sharing the app on socials 🙂🙏
> 
> Thanks in advance, j

08:38:04 [ASUSWRT] started.
08:38:04 [ASUSWRT] Connecting to the Router...
127.0.0.1 - - [24/Jan/2025 08:38:49] "POST /graphql HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2025 08:39:28] "POST /graphql HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2025 08:39:47] "POST /graphql HTTP/1.1" 200 -
08:40:06 [ARP Scan] In script 
08:40:06 [ARPSCAN] userSubnetsParam: 192.168.50.0/24 --interface=eth0
08:40:06 [Database] Opening DB
127.0.0.1 - - [24/Jan/2025 08:40:13] "POST /graphql HTTP/1.1" 200 -
08:40:53 [ASUSWRT] started.
08:40:53 [ASUSWRT] Connecting to the Router...
127.0.0.1 - - [24/Jan/2025 08:41:59] "POST /graphql HTTP/1.1" 200 -


 Not sure what this is telling me?

**Comment by jokob-sk** [comment]
Can you try to enter incorrect credentials and post the result vs correct credentials? 

I regrettably can't change what the Asus library logs - so if there is an obvious error, and 200 means everything OK then I'd consider this as solved.

**Comment by netExtra** [comment]
> Can you try to enter incorrect credentials and post the result vs correct credentials?
> 
> I regrettably can't change what the Asus library logs - so if there is an obvious error, and 200 means everything OK then I'd consider this as solved.

I was still getting HTTP 200 log messages from what I can see. What's interesting is that since the latest release, my usb ethernet connection is considered down. I disables the notification because it is reduntant. If the interface is down then I won't be able to connect to netalertx. But it is an interesting change.

**Comment by jokob-sk** [comment]
Hummm, I can't test a valid connection, but if I enter an incorrect IP I'm getting a pretty good log:

## INCORRECT SETTINGS

```
20:31:03 [ASUSWRT] started.
Using selector: EpollSelector
20:31:03 [ASUSWRT] Connecting to the Router...
Initializing a new interface to `192.168.1.1`
Initializing a new connection to `192.168.1.1`
Using provided session
Using session `<aiohttp.client.ClientSession object at 0x7f2ef5048ce0>`
Using `http` and port `80` with ssl flag `False`
Triggered method async_connect
Initializing connection to 192.168.1.1
Requesting authorization
Connection failed with error: ('Endpoint EndpointService.LOGIN not found', None)
Will try again in 5.0 seconds
Initializing connection to 192.168.1.1
Requesting authorization
Connection failed with error: ('Endpoint EndpointService.LOGIN not found', None)
Will try again in 10.0 seconds
```

This is clear. If you are then getting something like this on success, then I think this is a significant improvement and I would consider the issue as resolved:

## CORRECT SETTINGS

```
08:38:04 [ASUSWRT] Connecting to the Router...
127.0.0.1 - - [24/Jan/2025 08:38:49] "POST /graphql HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2025 08:39:28] "POST /graphql HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2025 08:39:47] "POST /graphql HTTP/1.1" 200 -
08:40:06 [ARP Scan] In script
08:40:06 [ARPSCAN] userSubnetsParam: 192.168.50.0/24 --interface=eth0
08:40:06 [Database] Opening DB
127.0.0.1 - - [24/Jan/2025 08:40:13] "POST /graphql HTTP/1.1" 200 -
08:40:53 [ASUSWRT] started.
08:40:53 [ASUSWRT] Connecting to the Router...
127.0.0.1 - - [24/Jan/2025 08:41:59] "POST /graphql HTTP/1.1" 200 -
```

**Comment by netExtra** [comment]
OK you've had another update within the last hour. I'm getting that image now.

**Comment by netExtra** [comment]
Whatever version you are running, I don't have it.

**Comment by jokob-sk** [comment]
Regrettably I'm not able to help with your environment. You can try to stop all nax containers, delete them and and delete the images. That's the only advice I can offer.

**Comment by netExtra** [comment]
> Regrettably I'm not able to help with your environment. You can try to stop all nax containers, delete them and and delete the images. That's the only advice I can offer.

I have you latest image from just under an hour ago and it's not giving me the same results. But no problem as this isn't a key requirement for me. But I would like to know if others are getting the same log messages you are, coz I'm getting nothing with incorrect credentials, but maybe something with correct credentials.

**Comment by netExtra** [comment]
This is all I get with your latest image:

Starting new HTTPS connection (1): api.github.com:443
https://api.github.com:443 "GET /repos/jokob-sk/NetAlertX/releases HTTP/1.1" 200 None
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:20212
 * Running on http://192.168.50.69:20212
[33mPress CTRL+C to quit[0m
[ASUSWRT] started.
[ASUSWRT] Connecting to the Router...

**Comment by jokob-sk** [comment]
You can ignore that message.

Also you need to save settings for them to apply. Running a plugin manually without saving settings will use saved settings only.

You can of course contribute with code directly if you have a better idea on how to solve this, but this is the extend of my ability right now I think.

**Comment by netExtra** [comment]
> You can ignore that message.
> 
> Also you need to save settings for them to apply. Running a plugin manually without saving settings will use saved settings only.
> 
> You can of course contribute with code directly if you have a better idea on how to solve this, but this is the extend of my ability right now I think.

Thanks. I did save settings then run manually. I just downloaded the latest dev image (from about 2 hours ago) and app.log shows absolutely nothing now. app_front.log shows it being added to the execution queue. But app.log shows nothing.

**Comment by jokob-sk** [comment]
Can you try to run the image completely without mounts? Might be a permission issue:

```
docker run -d --rm --network=host \
  -e TZ=Europe/Berlin \
  -e PORT=20211 \
  jokobsk/netalertx-dev:latest
```

**Comment by netExtra** [comment]
> Can you try to run the image completely without mounts? Might be a permission issue:
> 
> ```
> docker run -d --rm --network=host \
>   -e TZ=Europe/Berlin \
>   -e PORT=20211 \
>   jokobsk/netalertx-dev:latest
> ```

No change. Asuswrt starts but nothing happens with the logs. Am I supposed to use Sudo?

**Comment by jokob-sk** [comment]
Hmm, not sure what is going on with your system at the moment... You can
also access logs via /app/log so maybe give taht a try

**Comment by netExtra** [comment]
> Hmm, not sure what is going on with your system at the moment... You can
> also access logs via /app/log so maybe give taht a try
> […](#)
 
Tried everything. I don't get the log entries for incorrect Asuswrt access. Since the last image I downloaded 6 hours ago, I get even less info than before.

**Comment by jokob-sk** [comment]
Hmmm, what's your LOG_LEVEL?

**Comment by netExtra** [comment]
> Hmmm, what's your LOG_LEVEL?
> […](#)

Verbose.

What's weird is that logging issues got worse after my last dev update 6 hours ago.

**Comment by jokob-sk** [comment]
Could you please try to set it to debug? I;'m getting this on the debug level:

```
16:35:17 [ASUSWRT] Connecting to the Router...
Initializing a new interface to `192.168.1.1`
Initializing a new connection to `192.168.1.1`
Using provided session
Using session `<aiohttp.client.ClientSession object at 0x7fdc3b5dc350>`
Using `http` and port `80` with ssl flag `False`
Triggered method async_connect
Initializing connection to 192.168.1.1
Requesting authorization
Connection failed with error: ('Endpoint EndpointService.LOGIN not found', None)
Will try again in 5.0 seconds
Initializing connection to 192.168.1.1
Requesting authorization
Connection failed with error: ('Endpoint EndpointService.LOGIN not found', None)
Will try again in 10.0 seconds
Initializing connection to 192.168.1.1
Requesting authorization
Connection failed with error: ('Endpoint EndpointService.LOGIN not found', None)
Will try again in 20.0 seconds
```

**Comment by netExtra** [comment]
This is what I get from Debug:

13:39:08 [ASUSWRT] started.
Using selector: EpollSelector
13:39:08 [ASUSWRT] Connecting to the Router...
Initializing a new interface to `192.168.xx.xx`
Initializing a new connection to `192.168.xx.xx`
Using provided session
Using session `<aiohttp.client.ClientSession object at 0x7fae89b7a0>`
Using `https` and port `8443` with ssl flag `True`
Triggered method async_connect
Initializing connection to 192.168.xx.xx
Requesting authorization
Received authorization response
Connected to 192.168.xx.xx
Triggered method async_get_identity
Collecting device identity
Triggered method async_api_hook: nvram_get(serial_no);nvram_get(label_mac);nvram_get(lan_hwaddr);nvram_get(wan_hwaddr);nvram_get(productid);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);nvram_get(ledg_rgb1);nvram_get(ledg_rgb2);
Triggered method async_api_load: Endpoint.HOOK
Triggered method async_api_query: Endpoint.HOOK | hook=nvram_get(serial_no);nvram_get(label_mac);nvram_get(lan_hwaddr);nvram_get(wan_hwaddr);nvram_get(productid);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);nvram_get(ledg_rgb1);nvram_get(ledg_rgb2);
Sending `RequestType.POST` request to `192.168.xx.xx`
Response 200 received from Endpoint.HOOK
Reading data from endpoint Endpoint.HOOK
Identity collected
Identity read
Triggered method async_api_query: Endpoint.DEVICEMAP | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.DSL | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.ETHERNET_PORTS | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.FIRMWARE | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.FIRMWARE_NOTE | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.FIRMWARE_NOTE_AIMESH | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.HOOK | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.NETWORKMAPD | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.ONBOARDING | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.PORT_STATUS | node_mac=all
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.STATE | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.SYSINFO | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.TEMPERATURE | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.UPDATE_CLIENTS | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: Endpoint.VPN | None
Sending `RequestType.POST` request to `192.168.xx.xx`
Triggered method async_api_query: EndpointTools.NETWORK | None
Sending `RequestType.GET` request to `192.168.xx.xx`
Endpoints checked
Adding conditional rules for stock firmware
Added conditional state rule: AsusState.OPENVPN_CLIENT -> AsusData.VPNC
Added conditional state rule: AsusState.WIREGUARD_CLIENT -> AsusData.VPNC
Added data alias: AsusData.VPNC -> AsusData.OPENVPN_CLIENT
Added data alias: AsusData.VPNC -> AsusData.WIREGUARD_CLIENT
Added conditional data rule: AsusData.OPENVPN_SERVER -> <asusrouter.modules.data_finder.AsusDataFinder object at 0x7faed1d5e0>
Removed data rule: AsusData.DSL
Triggered method _check_state
Triggered method _check_prerequisites for datatype `AsusData.CLIENTS`
Triggered method _where_to_get_data
Endpoints to check: [<Endpoint.ONBOARDING: 'ajax_onboarding.asp'>, <Endpoint.UPDATE_CLIENTS: 'update_clients.asp'>]
Triggered method async_api_load: Endpoint.ONBOARDING
Triggered method async_api_query: Endpoint.ONBOARDING | 
Sending `RequestType.POST` request to `192.168.xx.xx`
Response 200 received from Endpoint.ONBOARDING
Reading data from endpoint Endpoint.ONBOARDING
Processing data from endpoint Endpoint.ONBOARDING
Triggered method async_api_load: Endpoint.UPDATE_CLIENTS
Triggered method async_api_query: Endpoint.UPDATE_CLIENTS | 
Sending `RequestType.POST` request to `192.168.xx.xx`
Response 200 received from Endpoint.UPDATE_CLIENTS
Reading data from endpoint Endpoint.UPDATE_CLIENTS
Reading modern update clients data
Processing data from endpoint Endpoint.UPDATE_CLIENTS
Triggered method _transform_data for `AsusData.AIMESH`
Triggered method _transform_data for `AsusData.CLIENTS`
Transforming clients data
Triggered method _check_flags
Triggered method _check_postrequisites for datatype `AsusData.CLIENTS`
Returning data for `AsusData.CLIENTS` with object type `<class 'dict'>`
Triggered method _return_state
Triggered method async_disconnect
Initializing disconnection from 192.168.xx.xx
Access error message: {'error_status': '8', 'captcha_on': '0', 'last_time_lock_warning': '0'}
13:40:45 [ARP Scan] In script 
13:40:45 [ARPSCAN] userSubnetsParam: 192.168.xx.xx/24 --interface=eth0
13:40:45 [Database] Opening DB
13:41:05 [INTRNT] In script
13:41:05 [INTRNT] INTRNT_DIG_GET_IP_ARG: -4 myip.opendns.com @resolver1.opendns.com
13:41:05 [INTRNT] - Retrieving Internet IP
13:41:15 [AVAHISCAN] In script
13:41:15 [Database] Opening DB
127.0.0.1 - - [25/Jan/2025 13:43:09] "POST /graphql HTTP/1.1" 200 -
127.0.0.1 - - [25/Jan/2025 13:43:42] "POST /graphql HTTP/1.1" 200 -
13:43:47 [ASUSWRT] started.
Using selector: EpollSelector
13:43:47 [ASUSWRT] Connecting to the Router...
Initializing a new interface to `192.168.xx.xx`
Initializing a new connection to `192.168.xx.xx`
Using provided session
Using session `<aiohttp.client.ClientSession object at 0x7fadf5ab10>`
Using `https` and port `8443` with ssl flag `True`
Triggered method async_connect
Initializing connection to 192.168.xx.xx
13:46:13 [ARP Scan] In script 
13:46:13 [ARPSCAN] userSubnetsParam: 192.168.xx.xx/24 --interface=eth0
13:46:13 [Database] Opening DB
13:46:52 [INTRNT] In script
13:46:52 [INTRNT] INTRNT_DIG_GET_IP_ARG: -4 myip.opendns.com @resolver1.opendns.com
13:46:52 [INTRNT] - Retrieving Internet IP

**Comment by netExtra** [comment]
> Could you please try to set it to debug? I;'m getting this on the debug level:
> 
> ```
> 16:35:17 [ASUSWRT] Connecting to the Router...
> Initializing a new interface to `192.168.1.1`
> Initializing a new connection to `192.168.1.1`
> Using provided session
> Using session `<aiohttp.client.ClientSession object at 0x7fdc3b5dc350>`
> Using `http` and port `80` with ssl flag `False`
> Triggered method async_connect
> Initializing connection to 192.168.1.1
> Requesting authorization
> Connection failed with error: ('Endpoint EndpointService.LOGIN not found', None)
> Will try again in 5.0 seconds
> Initializing connection to 192.168.1.1
> Requesting authorization
> Connection failed with error: ('Endpoint EndpointService.LOGIN not found', None)
> Will try again in 10.0 seconds
> Initializing connection to 192.168.1.1
> Requesting authorization
> Connection failed with error: ('Endpoint EndpointService.LOGIN not found', None)
> Will try again in 20.0 seconds
> ```

OK finally getting the not correct messages on debug. I can see exactly where it is failing.

**Comment by jokob-sk** [comment]
Phew, glad to hear that, was getting desperate. :) Here is what I've added to the README:

- If you have troubles configuring the plugin set the `LOG_LEVEL='debug'` to get a more detailed error message.

**Comment by netExtra** [comment]
> Phew, glad to hear that, was getting desperate. :) Here is what I've added to the README:
> 
> * If you have troubles configuring the plugin set the `LOG_LEVEL='debug'` to get a more detailed error message.

This isn't key functionality for me at the moment. But I would still like to know why even with the correct information I'm getting this message. I definitely saved the new details with the correct user/pass and port. But may be that's for another ticket so you can close this one if you wish.

**Comment by jokob-sk** [comment]
releasing in 15 min -> closing
